"""empty message

Revision ID: 87c03ee7f382
Revises: d95c7fb0f421
Create Date: 2022-03-06 20:37:08.530414

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '87c03ee7f382'
down_revision = 'd95c7fb0f421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
