"""empty message

Revision ID: c72b32ea2da2
Revises: bd0d270be7ce
Create Date: 2022-03-06 05:59:13.326453

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c72b32ea2da2'
down_revision = 'bd0d270be7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
