"""empty message

Revision ID: d95c7fb0f421
Revises: c72b32ea2da2
Create Date: 2022-03-06 07:13:31.104341

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd95c7fb0f421'
down_revision = 'c72b32ea2da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('song', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'created_at')
    op.drop_column('song', 'updated_at')
    # ### end Alembic commands ###
