"""empty message

Revision ID: ea354314593d
Revises: 3d0f6d4d5897
Create Date: 2022-04-18 16:15:12.567687

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'ea354314593d'
down_revision = '3d0f6d4d5897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
