"""empty message

Revision ID: 3293815eb23c
Revises: cc36a024e8ed
Create Date: 2022-11-03 14:16:45.119467

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '3293815eb23c'
down_revision = 'cc36a024e8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LinkGroupUser', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('LinkGroupUser', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LinkGroupUser', 'created_at')
    op.drop_column('LinkGroupUser', 'updated_at')
    # ### end Alembic commands ###
