"""empty message

Revision ID: 5591a516fc47
Revises: 3293815eb23c
Create Date: 2023-03-04 23:15:59.254665

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from app.models.user_model import IGenderEnum
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '5591a516fc47'
down_revision = '3293815eb23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(IGenderEnum), nullable=True))    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'gender')
    # ### end Alembic commands ###
